name: pb_frontend
description: Private Board Flutter client
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  go_router: ^13.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
flutter:
  uses-material-design: true
